// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAik7jZrPt8Raaw9_Jmtv9F9CC-oo5DuLE',
    appId: '1:978172978611:web:0c67e1fb28fbcff8b017c6',
    messagingSenderId: '978172978611',
    projectId: 'herbs-948b7',
    authDomain: 'herbs-948b7.firebaseapp.com',
    storageBucket: 'herbs-948b7.appspot.com',
    measurementId: 'G-3221T5SGHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gSnHRGaDdNEZMscxsrUJ-DET6rsomik',
    appId: '1:978172978611:android:0fa419eb570e2f5eb017c6',
    messagingSenderId: '978172978611',
    projectId: 'herbs-948b7',
    storageBucket: 'herbs-948b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAmkTYQ2oJXVwg20PVtgfN8lKwoDNQD8',
    appId: '1:978172978611:ios:2d32b7efe9a1f957b017c6',
    messagingSenderId: '978172978611',
    projectId: 'herbs-948b7',
    storageBucket: 'herbs-948b7.appspot.com',
    iosClientId: '978172978611-sevc0opo6enu22k26nsrmfkrv4htkcj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAmkTYQ2oJXVwg20PVtgfN8lKwoDNQD8',
    appId: '1:978172978611:ios:2d32b7efe9a1f957b017c6',
    messagingSenderId: '978172978611',
    projectId: 'herbs-948b7',
    storageBucket: 'herbs-948b7.appspot.com',
    iosClientId: '978172978611-sevc0opo6enu22k26nsrmfkrv4htkcj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
